<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$active_group = 'smsgw';
$active_record = TRUE;
 
$db['smsgw']['username'] = 'root';
$db['smsgw']['database'] = 'gammu';
$db['smsgw']['password'] = '';
$db['smsgw']['hostname'] = 'localhost';
$db['smsgw']['dbdriver'] = 'mysql';
$db['smsgw']['dbprefix'] = '';
$db['smsgw']['pconnect'] = FALSE;
$db['smsgw']['db_debug'] = FALSE;
$db['smsgw']['cache_on'] = FALSE;
$db['smsgw']['cachedir'] = '';
$db['smsgw']['char_set'] = 'utf8';
$db['smsgw']['dbcollat'] = 'utf8_general_ci';
$db['smsgw']['swap_pre'] = '';
$db['smsgw']['autoinit'] = FALSE;
$db['smsgw']['stricton'] = FALSE;

$active_group = 'live';
$active_record = TRUE;
$db['live']['hostname'] = '127.0.0.1';
$db['live']['username'] = 'root';
$db['live']['password'] = '';
$db['live']['database'] = 'alumni';
$db['live']['port'] = '3306';
$db['live']['dbdriver'] = 'mysqli';
$db['live']['dbprefix'] = '';
$db['live']['pconnect'] = TRUE;
$db['live']['db_debug'] = TRUE;
$db['live']['cache_on'] = FALSE;
$db['live']['cachedir'] = '';
$db['live']['char_set'] = 'utf8';
$db['live']['dbcollat'] = 'utf8_general_ci';
$db['live']['swap_pre'] = '';
$db['live']['autoinit'] = TRUE;
$db['live']['stricton'] = FALSE;